//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bean
    {
        public int ID { get; set; }
        public string Origin { get; set; }
        public string Region { get; set; }
        public string Farm { get; set; }
        public string Variety { get; set; }
        public int Altitude { get; set; }
        public string Roast { get; set; }
        public string Flavor { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public string State { get; set; }
    }
}
