//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db5a880438084247f18360a8af0029f810Entities : DbContext
    {
        public db5a880438084247f18360a8af0029f810Entities()
            : base("name=db5a880438084247f18360a8af0029f810Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bean> Beans { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
    }
}
